In [1]:
# KNN Classification
from pandas import read_csv
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier , KNeighborsRegressor

In [52]:

#names = [
 #   'hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothed', 'backbone']

dataframe = read_csv("C:/Users/Narsing/Downloads/Assigments data science/13th--Assignment--KNN/Zoo.csv")
array = dataframe.values
X = array[:, 1:10]
Y = array[:, 10]



array([1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=object)

In [3]:

dataframe.head()

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   type  
0     1  
1     1  
2     4  
3     1  
4     1

In [5]:
dataframe.drop('animal name',axis=1)

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  type  
0           1         1         0     0     4     0         0        1     1  
1           1         1         0     0     4     1         0        1     1  
2           1         0         0     1     0     1         0        0     4  
3           1         1         0     0     4     0         0        1     1  
4           1         1         0     0     4     1         0        1     1  
..        ...       ...       ...   ...   ...   ...       ...      ...   ...  
96          1         1         0     0     2     1         0        1     1  
97          0         1         1     0     6     0         0        0     6  
98          1         1         0     0     4     1         0        1     1  
99          0         1         0     0     0     0         0        0     7  
100         1         1         0     0     2     1         0        0     2  

[101 rows x 17 columns]

In [53]:


#results = accuracy_score(model, X, Y, cv=10)


In [54]:
from sklearn.model_selection import train_test_split
model = KNeighborsClassifier(n_neighbors=11)

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2,random_state=42)
X_train

array([[0, 0, 1, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 1, 1],
       [1, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 1],
       [1, 0, 0, 1, 0, 0, 1, 1, 1],
       [1, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 1, 1],
       [1, 0, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 1, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 1, 1],
       [1, 0, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 1, 1,

In [63]:
from sklearn.preprocessing import LabelEncoder

# Assuming y contains your labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_encoded

#model = KNeighborsClassifier(n_neighbors=14)
#y_pred = model.predict(X_test)

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [65]:
model.fit(X_train,y_train)

ValueError: Unknown label type: 'unknown'

In [64]:
pred_test = model.predict(X_test)

AttributeError: 'KNeighborsClassifier' object has no attribute 'n_samples_fit_'